### ISSUE TITLE
clone 下来好多问题

### ISSUE THREAD

**Issue by wh-Coder** [huangche007/vue-jd#1]
1. 登录之后报错
Login.vue?1c5f:56 Uncaught (in promise) ReferenceError: userInfo is not defined
    at eval (eval at <anonymous> (build.js:1381), <anonymous>:57:45)
2. tabs 点击没有高亮
好多啊。。。
楼主加油，跑通了，我再学习

**Comment by huangche007** [comment]
你说的第一个问题，对userinfo做个判断就行，当时写的不是那么的完整，难免会有bug，其实有些bug也是故意留的，^_^;第二个问题是我把项目中的所有交互都抽成模块的方式来进行开发，在我使用vue-lazyload后，发现分类页的tab效果居然没了，我也感到很奇怪，目前也没有解决，如果有好的解决方式尽量提出，最近比较忙
