### ISSUE TITLE
运行 npm run dev 后出现下列问题

### ISSUE THREAD

**Issue by ed19831121** [huangche007/vue-jd#2]
ERROR in ./src/main.js
Module not found: Error: Can't resolve 'Less' in '/home/linux/nodejs/vue-jd/src'
 @ ./src/main.js 4:0-24
 @ multi (webpack)-dev-server/client?http://localhost:8081 webpack/hot/dev-server ./src/main.js

**Comment by huangche007** [comment]
应该是Less没有安装成功的缘故
