### ISSUE TITLE
正确的账号登录时报错

### ISSUE THREAD

**Issue by suguoyao** [huangche007/vue-jd#3]
报userinfo未定义，检查发现是dispatch setUserInfo方法时，传的参数有问题，不是userInfo而是_this.userInfo

**Comment by huangche007** [comment]
OK，谢谢反馈，最近在做公司项目比较忙，我有时间会处理的

**Comment by huangche007** [comment]
国庆节修复

**Comment by huangche007** [comment]
@526878729 你在与_this.userInfo这部分代码的方法第一行添加const _this = this;
