### ISSUE TITLE
你好，我想问一下这里怎样处理跨域访问的

### ISSUE THREAD

**Issue by lixiusen** [huangche007/vue-jd#7]

**Comment by huangche007** [comment]
@lixiusen 跨域的方式有很多种，通常用得比较多的就是jsonp、反向代理、后端设置CORS的方式，其中我这个项目里面用到的就是设置CORS的方式来解决跨域的问题,看下项目里面的server.js文件里面
`server.all('*', function(req, res, next) {
    res.header('Access-Control-Allow-Origin', '*');
    res.header('Access-Control-Allow-Headers', 'Content-Type, Content-Length, Authorization, Accept, X-Requested-With , yourHeaderFeild');
    res.header('Access-Control-Allow-Methods', 'PUT, POST, GET, DELETE, OPTIONS');

    if (req.method == 'OPTIONS') {
        res.send(200);
        /make the require of options turn back quickly/
    } else {
        next();
    }
});`
这段代码就是设置CORS方式处理跨域
